apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
      type: ClusterIP
      selector:
          app: my-daemonset-nginx
      ports:
           - name: http
             port: 30080
             targetPort: 8080		
