apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-role-pod-reader # Replace with the actual name of the ClusterRole
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: default

