apiVersion: v1
kind: Service
metadata:
  name: my-svc1
spec:
      type: ClusterIP
      selector:
          app: my-nginx
      ports:
           - name: http
             port: 8080
             targetPort: 80 
