apiVersion: v1
kind: Pod
metadata:
    name: my-pod-ns2
    namespace: my-ns2
spec:
    containers:
       - name: my-nginx
         image: nginx:latest
         ports:
                 - containerPort: 80

